apiVersion: apps/v1
kind: Deployment
metadata:
  name: keudste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keudste
  template:
    metadata:
      labels:
        app: keudste
    spec:
      containers:
      - image: okteto.dev/keudste:latest
        name: keudste
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "860d52b1-5af8-4c3d-8ee1-67beed98af7d"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "860d52b1-5af8-4c3d-8ee1-67beed98af7d"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
